In [14]:
import os
import warnings
warnings.filterwarnings("ignore")
import torch
from torch import Tensor
import torch.nn as nn
import pandas as pd
import numpy as np
import random

In [2]:
base_data_dir = '../../data'
word2vec_dir = 'word2vec/ptb'
ptb_train_fname = 'ptb.train.txt'

In [3]:
with open(os.path.join(base_data_dir, word2vec_dir, ptb_train_fname)) as f:
    raw_text = f.read()

In [64]:
x = torch.tensor([[0], [1], [2]])
y = torch.tensor([[4, 5, 6], [7,8,9], [1,2,3]])
embed = nn.Embedding(20, 4)
x_ = embed(x)
y_ = embed(y)

In [65]:
y_

tensor([[[ 2.0749, -1.2254,  0.9129, -1.0962],
         [-0.2753,  1.0858,  0.1818, -1.4332],
         [-1.8281,  0.9873,  1.0029,  0.4711]],

        [[ 0.0777, -0.5323, -1.3714,  0.6701],
         [-0.3558,  0.0751, -0.8888,  2.1104],
         [ 0.3840,  0.5332,  0.8989,  0.6159]],

        [[-1.3351, -0.8751, -1.2397,  0.3668],
         [-1.5908, -0.3215,  0.5512, -1.0893],
         [-1.2385,  0.1078, -0.2176,  0.1844]]], grad_fn=<EmbeddingBackward0>)

In [66]:
y

tensor([[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]])

In [67]:
x_

tensor([[[-1.0497, -1.7856,  1.2722,  1.1696]],

        [[-1.3351, -0.8751, -1.2397,  0.3668]],

        [[-1.5908, -0.3215,  0.5512, -1.0893]]], grad_fn=<EmbeddingBackward0>)

In [70]:
y_

tensor([[[ 2.0749, -1.2254,  0.9129, -1.0962],
         [-0.2753,  1.0858,  0.1818, -1.4332],
         [-1.8281,  0.9873,  1.0029,  0.4711]],

        [[ 0.0777, -0.5323, -1.3714,  0.6701],
         [-0.3558,  0.0751, -0.8888,  2.1104],
         [ 0.3840,  0.5332,  0.8989,  0.6159]],

        [[-1.3351, -0.8751, -1.2397,  0.3668],
         [-1.5908, -0.3215,  0.5512, -1.0893],
         [-1.2385,  0.1078, -0.2176,  0.1844]]], grad_fn=<EmbeddingBackward0>)

In [68]:
(x_.expand(-1, 3, -1) * y_).sum(dim=-1)

tensor([[-0.1108, -3.0948,  1.9831],
        [ 2.3080,  2.2853, -1.8678],
        [ 1.3224,  4.1245,  1.6148]], grad_fn=<SumBackward1>)

In [69]:
torch.bmm(x_, y_.permute(0,2,1))

tensor([[[-0.1108, -3.0948,  1.9831]],

        [[ 2.3080,  2.2853, -1.8678]],

        [[ 1.3224,  4.1245,  1.6148]]], grad_fn=<BmmBackward0>)

In [71]:
masks = torch.tensor([[1, 1, 1, 0, 0], [1,1,0,0,0]])
masks / masks.sum(dim=1, keepdim=True)

tensor([[0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000]])